### ISSUE TITLE
Include array as a load option

### ISSUE THREAD

**Issue by ktoddbrown** [JGCRI/RCMIP5#121]
We want the flexibility to represent the underlying data as both an array and data.frame.

Right now the following accept array representations:
RCMIP5 functions
loadCMIP5
makeGlobalStat
makeAnnualStat

This needs to be extended to include:
makeMonthlyStat
makeZStat
mergeExperiments

**Comment by bpbond** [comment]
I've added code to `test_loadCMIP5` so that it runs most tests on both data representations. The other test files will be trickier, and we'll need to think about how we want to do this.

**Comment by bpbond** [comment]
@ktoddbrown With commit e64f313, the first testing case (lines 26-20) of `test_makeAnnualStat.R` now tests both the array and data.frame implementations. You'll see I've written a couple of short helper functions `nvals` and `vals` that abstract away getting the data from a cmip5data object, so the testing code just loops through the available implementations and runs the exact same code using each.

Currently the array implementation is commented out (see line 15) because the array code in `makeAnnualStat` is throwing some kind of error.

**Comment by bpbond** [comment]
`makeZstat` and `makeMonthlyStat` still need array implementations.

**Comment by bpbond** [comment]
Moved from issue #125 : Along these lines, a data.frame version of regridding needs to be added. It should just be a function of sorting the lat/lon and then apply the same matrix by Z-time slice. I worked up some additional test cases but ran out of time for actual implementation today. @ktoddbrown

**Comment by ktoddbrown** [comment]
makeZstat done bce8750cf7f5e92d337d00caeb9c1153cba43d85

**Comment by ktoddbrown** [comment]
makeMonthlyStat done d8df831a852a2c49326ec4034597804df570f5ae

**Comment by ktoddbrown** [comment]
Fixed makeAnnualStat: bc6479b2e2ada69ee81fe499949e85ef5a223659 and 1b1196fc6557a703eab0296a45faffe4249199a2

**Comment by ktoddbrown** [comment]
mergeExperiments done 6dbf6fddaa347d3a3c0e248de0a117d3a653f15e

[side note: commenting in a single issue is much less satisfying then clicking close.]

**Comment by ktoddbrown** [comment]
extend regrid implementation to data.frame 8c30ae18f61378f5d3596fddec789609d5b3e46b 

@bpbond is this task done now?

**Comment by bpbond** [comment]
I think so. Closing.
